<?php

/*
 * This file is licensed under GPLv2+.
*/

/**
 * @file
 * Provides UnionPay interface for drupal.
 */

/**
 * Implementation of hook_menu().
 */
function unionpay_menu() {
	$items['admin/config/services/unionpay'] = array(
		'title' => 'Unionpay settings',
		'description' => 'Unionpay merchant settings.',
		'access arguments' => array('access administration pages'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('unionpay_admin_form'),
	);
	$items['charge/unionpay'] = array(
		'access callback' => 'unionpay_response_access',
		'type' => MENU_CALLBACK,
		'page callback' => 'unionpay_response',
	);
	return $items;
}

function unionpay_admin_form($form, $form_state) {
	$form['security_key'] = array(
		'#type' => 'textfield',
		'#title' => t('Security Key (@code)',array('@code'=>'security_key')),
		'#default_value' => variable_get('unionpay_security_key', ''),
		'#required' => TRUE,
	);
	$form['merid'] = array(
		'#type' => 'textfield',
		'#title' => t('Merchant ID (@code)',array('@code'=>'merId')),
		'#default_value' => variable_get('unionpay_merid', ''),
		'#required' => TRUE,
	);
	$form['acqcode'] = array(
		'#type' => 'textfield',
		'#title' => t('Acquirer BIN (@code)',array('@code'=>'acqCode')),
		'#default_value' => variable_get('unionpay_acqcode', ''),
		'#required' => TRUE,
	);
	$form['mercode'] = array(
		'#type' => 'textfield',
		'#title' => t('Merchat Code (@code)',array('@code'=>'merCode')),
		'#default_value' => variable_get('unionpay_mercode', ''),
		'#required' => TRUE,
	);
	$form['merabbr'] = array(
		'#type' => 'textfield',
		'#title' => t('Merchant Name (@code)',array('@code'=>'merAbbr')),
		'#default_value' => variable_get('unionpay_merabbr', ''),
		'#required' => TRUE,
	);
	return system_settings_form($form);
}

function unionpay_admin_form_submit($form, $form_state) {
	$settings=array(
		'security_key', 'merid', 'acqcode', 'mercode', 'merabbr'
	);
	foreach($settings as $s) {
		variable_set('unionpay_'.$s,$form_state['values'][$s]);
	}
}

